apiVersion: v1
kind: Service
metadata:
  name: color-service
spec:
  ports:
    - nodePort: 31355
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: color
  type: NodePort
